制品库: "xpath==/html[1]/body[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[7]/a[1]/div[1]"
半成品库: "xpath==/html[1]/body[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[7]/a[2]/div[1]"
成品库:  "xpath==/html[1]/body[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[7]/a[3]/div[1]"
镜像库: "xpath==/html[1]/body[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[7]/a[4]/div[1]"
制品库面包屑: "xpath==/html[1]/body[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/span[2]/span[1]"
我的全部: "xpath==/html[1]/body[1]/div[2]/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]"
我是管理员: "xpath==/html[1]/body[1]/div[2]/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]"
我的收藏: "xpath==/html[1]/body[1]/div[2]/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]"
收藏按钮: "xpath==/html[1]/body[1]/div[2]/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[7]/span[1]"
获取制品库名称: "css==div._root_j11bm_1:nth-child(3) div._root_19uym_1 div._right_19uym_146 div._main_19uym_154 div.customScrollBar._content_19uym_169 div.ant-table-wrapper._root_1njqu_1.ant-table-middle:nth-child(3) div.ant-spin-nested-loading div.ant-spin-container div.ant-table div.ant-table-container div.ant-table-content table:nth-child(1) tbody.ant-table-tbody:nth-child(3) tr.ant-table-row.ant-table-row-level-0:nth-child(1) td.ant-table-cell:nth-child(1) > a:nth-child(1)"
新建半成品库: "xpath==//span[contains(text(),'新建半成品库')]"
输入仓库名称: "xpath==//input[@id='repoName']"
输入仓库描述: "xpath==//textarea[@id='repoDesc']"
确定: "xpath==//span[contains(text(),'确 定')]"
仓库名称: "xpath==//body[1]/div[2]/div[2]/div[1]/div[2]/div[2]/div[1]/section[1]/main[1]/div[1]/div[1]/div[1]/div[1]/span[1]"
包列表: "xpath==/html[1]/body[1]/div[2]/div[2]/div[1]/div[2]/div[2]/div[1]/section[1]/main[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]"
新建包: "xpath==//span[contains(text(),'新建包')]"
输入包名: "xpath==//input[@id='pkgName']"
获取包名: "xpath==//span[contains(text(),'apple.com')]"
删除包按钮:  "xpath==//tbody/tr[1]/td[6]/div[1]/span[1]"
确认删除包: "xpath==//span[contains(text(),'确 认')]"
点击新创建的半成品: "xpath==//a[contains(text(),'uitest_create')]"
关联项目tab: "xpath==/html[1]/body[1]/div[2]/div[2]/div[1]/div[2]/div[2]/div[1]/section[1]/main[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[3]/div[1]"
关联项目: "xpath==//span[contains(text(),'关联项目')]"
点击选择项目: "xpath==//body/div[@id='root']/div[@id='mainRoot']/div[1]/div[2]/div[2]/div[1]/section[1]/main[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]"
选择项目: "xpath==/html[1]/body[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]"
获取关联项目名称: "xpath==//body[1]/div[2]/div[2]/div[1]/div[2]/div[2]/div[1]/section[1]/main[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[1]"
取消关联: "xpath==//tbody/tr[1]/td[5]/span[1]"
删除制品库tab: "xpath==/html[1]/body[1]/div[2]/div[2]/div[1]/div[2]/div[2]/div[1]/section[1]/main[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[8]/div[1]"
删除制品库按钮: "xpath==//span[contains(text(),'删除制品库')]"
输入制品库名称删除: "xpath==/html[1]/body[1]/div[2]/div[2]/div[2]/div[1]/div[2]/div[1]/div[2]/div[2]/div[3]/input[1]"
确认删除: "xpath==//span[contains(text(),'确认删除')]"
